import { createTheme } from "office-ui-fabric-react/lib/Styling";

export default createTheme({
    isInverted: true,
    palette: {
      "themePrimary": "#040505",
      "themeLighterAlt": "#dce1e1",
      "themeLighter": "#bcc6c6",
      "themeLight": "#9eaaaa",
      "themeTertiary": "#828f8f",
      "themeSecondary": "#667373",
      "themeDarkAlt": "#4c5858",
      "themeDark": "#333c3c",
      "themeDarker": "#1b2121",
      "neutralLighterAlt": "#f8f8f8",
      "neutralLighter": "#f4f4f4",
      "neutralLight": "#eaeaea",
      "neutralQuaternaryAlt": "#dadada",
      "neutralQuaternary": "#d0d0d0",
      "neutralTertiaryAlt": "#c8c8c8",
      "neutralTertiary": "#d3cfcf",
      "neutralSecondary": "#a6a0a0",
      "neutralPrimaryAlt": "#7d7676",
      "neutralPrimary": "rgb(51,51,51)",
      "neutralDark": "#514d4d",
      "black": "#3c3838",
      "white": "#ffffff",
      "primaryBackground": "#ffffff",
      "primaryText": "rgb(51,51,51)",
      "bodyBackground": "#ffffff",
      "bodyText": "rgb(51,51,51)",
      "disabledBackground": "#f4f4f4",
      "disabledText": "#c8c8c8"
    } as any,
});
